# Generated by Django 4.2.7 on 2025-09-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanalysis',
            name='analysis_method',
            field=models.CharField(default='openai', help_text='Method used for analysis (openai/mock)', max_length=10),
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence score from 0.0 to 1.0'),
        ),
    ]
